### ISSUE TITLE
Extension fails to load in Firefox 62.0.3 (64-bit)

### ISSUE THREAD

**Issue by mhaaz** [ostreifel/Attachments-Group#12]
The extension is really great and useful. 
However, since the rebranding from VSTS to AzureDevOps, it has stopped working for me on the latest stable Firefox release.

![image](https://user-images.githubusercontent.com/18725890/46722158-280d4b80-cc75-11e8-97eb-afde807312c0.png)

It might be a browser specific issue, since both Chrome and Edge load the extension w/o any trouble. Any hints on possible solutions or further troubleshooting steps are appreciated :)

**Comment by ostreifel** [comment]
I'm having difficulty repro-ing this.

FF version 62.0.3 (64 bit)
Tried both \<account\>.visualstudio.com and dev.azure.com/\<account\> url formats.

To assist with resolution of this can you [send a fiddler trace](https://www.telerik.com/fiddler/fiddlercap) to ottost@microsoft.com? Make sure to start the fiddler trace before refreshing the page

**Comment by ostreifel** [comment]
Closing this issue b/c of staleness. Please reopen if you find additional information that may help to resolve it.
