### ISSUE TITLE
Cannot see the extension at all

### ISSUE THREAD

**Issue by Chak209** [ostreifel/Attachments-Group#14]
Hi,

Does this work on TFS 2018 - I cannot see any sign of the extension in any of the work items ?

Thanks.

**Comment by ostreifel** [comment]
https://github.com/ostreifel/Attachments-Group/blob/master/details.md#configuration-using-process-template
![image](https://user-images.githubusercontent.com/5203542/49038339-85038900-f171-11e8-810c-375848f14d1d.png)
As you are on premises extensions will not be added to any of the workitems until you [update the process template](https://docs.microsoft.com/en-us/azure/devops/reference/update-customized-process-template?view=tfs-2018) for each work item you want to have the extension.
