### ISSUE TITLE
after addding attachment - no option to save 

### ISSUE THREAD

**Issue by danmorgen** [ostreifel/Attachments-Group#15]
TFS 2018.3
google chrome v71

added attachment to attachment group control. 
yet "save" button not enabled. must perform another field update to enable it

same with removing. attachment removed, save yet not enabled but attachment not shown in attachments group. still remains in attachments classic tab

**Comment by ostreifel** [comment]
There is no option to save because the attachment group saves on change - no dirty state to save.
All operations on the attachments group save immediately and if they don't there will be an error message displayed.
