### ISSUE TITLE
Does not work with IE11

### ISSUE THREAD

**Issue by Rumpfinger** [ostreifel/Attachments-Group#2]
Content is not displayed + 'Add Files' Link is missing if IE11is used.
![2018-04-01 12_25_11-pbis - internet explorer](https://user-images.githubusercontent.com/23439814/38172198-394a98dc-3597-11e8-83f0-ae8afec8ca90.jpg)

**Comment by ostreifel** [comment]
![image](https://user-images.githubusercontent.com/5203542/38183245-bacaabb6-35f3-11e8-80a2-a9d31f9438ff.png)
I am not having the same experience on ie. 

Is this vsts or tfs?
What version of tfs? 
Are there any errors in the console (f12)?

**Comment by Rumpfinger** [comment]
it's TFS 2017 update 2, not VSTS
regards
Josef

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by ostreifel** [comment]
Updated.

Issue was that only newer versions of tfs polyfill promises for ie.
