### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by LarsKemmann** [ostreifel/Attachments-Group#3]
Hello! I'd really like to use this extension, but I have a question. What would it take to allow the Attachments Group to (optionally) include showing attachments from Parent-linked work items? For example, in our team we typically have screen wireframes attached to Features in the backlog, and User Stories as children of each Feature to represent development of different sections of the corresponding screen.
It would be wonderful, for our situation, if I could open up a User Story while we're reviewing the acceptance criteria as a team, and see the relevant wireframe attachments (from the parent Feature as well as any attachments that are directly on the User Story) right there while estimating the story points.
What might be involved in making that happen?

**Comment by ostreifel** [comment]
Getting the attached files for the parent is fairly trivial.  I'm would want to explore how to properly show that the file is of the parent not the current wi to the user. My first response would be to overlay some kind of foreground image of the thumbnail/icon shown in the attachments grid.

**Comment by ostreifel** [comment]
Added it to the extension. Please let me know what you think.

**Comment by LarsKemmann** [comment]
Wow, it's _fantastic_! Thank you Otto! Works exactly as I had hoped. This is going to be great for our team workflow!

![image](https://user-images.githubusercontent.com/5834429/38422325-4a1abf54-3978-11e8-92ad-0c873838a615.png)
