### ISSUE TITLE
Please help compiling in VSCode

### ISSUE THREAD

**Issue by wjadevries** [ostreifel/Attachments-Group#32]
I like your extension and would like to contribute some features to it.
But after downloading the project and opening it in VS Code, I cannot get it to compile to a working version.
Can you please tell me what npm modules I have to include?
I'm missing the 'dist' folder, so I guess I need to execute some npm commands.

Thanks,

Wessel

**Comment by ostreifel** [comment]
```
npm install -g typings tfx-cli
npm install
npm run package-dev
```

**Comment by wjadevries** [comment]
Thanks!


Met vriendelijke groeten / Kind regards,


Wessel de Vries
06 - 2499 7783

www.wjadevries.nl<http://www.wjadevries.nl/>

WJA de Vries ICT Consultancy
Sluisoordlaan 341
7323EN Apeldoorn
KvK 57722331

Van: Otto Streifel <notifications@github.com>
Verzonden: maandag 11 mei 2020 0:21
Aan: ostreifel/Attachments-Group <Attachments-Group@noreply.github.com>
CC: Wessel de Vries <wessel@wjadevries.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ostreifel/Attachments-Group] Please help compiling in VSCode (#32)


npm install -g typings tfx-cli

npm install

npm run package-dev
