### ISSUE TITLE
Ability to preview images, .png, .jpeg, .gif, on the card face as per Trello

### ISSUE THREAD

**Issue by jonnyt2002** [ostreifel/Attachments-Group#37]
Hi, do you have plans to allow images to be previewed on the card face as per [Trello]( https://help.trello.com/article/769-adding-attachments-to-cards#:~:text=Click%20the%20front%20of%20the,desktop%20on%20to%20the%20card.).

If so, this would be a hugely powerful plugin for art and game teams. 

Thank you for your help and great job!

**Comment by ostreifel** [comment]
The extension is limited by what is available to extension apis on azure boards. The best way to add previews on the cards right now would probably be to write a chrome extension to insert them as chrome extensions have far fewer limitations.
