### ISSUE TITLE
I'd like to contribute a PDF icon

### ISSUE THREAD

**Issue by LarsKemmann** [ostreifel/Attachments-Group#4]
I'd like to contribute an icon for PDF file types. I found the code where you're switching based on file extension, but I don't know how the `icon(...)` function converts that to an actual icon graphic. Is there a VSTS-provided library that implements that?

If you can point me in the right direction I'd be happy to submit a PR.

Thanks!

**Comment by ostreifel** [comment]
I was getting my icons from https://developer.microsoft.com/en-us/fabric#/styles/icons

Adding their pdf icon.
![image](https://user-images.githubusercontent.com/5203542/38435174-bc1510ac-3985-11e8-8ff6-f8729fc57b92.png)

**Comment by LarsKemmann** [comment]
Thank you!!
