### ISSUE TITLE
Preview for PDF files?

### ISSUE THREAD

**Issue by LarsKemmann** [ostreifel/Attachments-Group#5]
So this might require a viewer component or something (maybe an iframe would do it?), but it would be great if we could show PDF attachments in a full-screen preview on mouse-click rather than having to download the file and open it in a separate tab.

**Comment by ostreifel** [comment]
Yeah, api is not letting me set download to false either. If you can find a way to show it in the tab the first time without downloading or someway to preview like with images let me know.

**Comment by ostreifel** [comment]
1.0.56 adds support in mozilla and chrome.

**Comment by ostreifel** [comment]
1.1.1 adds preview support for mp4s 
1.1.14 add preview support for text files

**Comment by LarsKemmann** [comment]
@ostreifel _Wow_, you work fast! That is fantastic, thank you so much!
