### ISSUE TITLE
Missing padding for new work item state

### ISSUE THREAD

**Issue by cschleiden** [ostreifel/Attachments-Group#6]
There needs to be some padding on the left to align with the group header:

![image](https://user-images.githubusercontent.com/2201819/38710514-b1f74212-3e75-11e8-8afb-e470ec79c5fa.png)

**Comment by ostreifel** [comment]
updated. e84a264a5a69a3a82226abcabd771b779e3e5805

**Comment by cschleiden** [comment]
Thanks!
